# Generated by Django 2.1.1 on 2018-09-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='starred',
            new_name='star',
        ),
    ]
